---
- name: Install httpd
  yum:
    name: nginx
    state: present

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Clone the HTML app from GitHub
  git:
    repo: https://github.com/srinivasarao-ceq/sample-html-app.git
    dest: /home/ec2-user
    version: main  # Replace with the branch or tag you want to deploy

- name: Copy HTML code to destination
  copy:
    src: /home/ec2-user/sample-html-app/*
    dest: /usr/share/nginx/html/
  notify: Restart Apache

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true